#ifndef NBFS_LAYOUT_H
#define NBFS_LAYOUT_H

#define NBFS_BOOT_BLOCK          0
#define NBFS_SUPERBLOCK_BLOCK    1
#define NBFS_BLOCK_BITMAP_BLOCK  2
#define NBFS_INODE_BITMAP_BLOCK  3
#define NBFS_INODE_TABLE_BLOCK   4
#define NBFS_INODE_TABLE_BLOCKS 64

#define NBFS_DATA_BLOCK \
(NBFS_INODE_TABLE_BLOCK + NBFS_INODE_TABLE_BLOCKS)

#endif
