#!/usr/bin/env python3
"""Pack the NeoBench system tree into the ROM.

    python3 tools/mkpfs.py system boot/rom/pfs_data.c

Walks the tree rooted at the first argument and writes a C translation
unit holding every file as a const byte array plus a flat node table
indexes by parent.  That is the whole PFS: NeoBench has no block device
to read a filesystem from, so the directory tree the desktop browses and
the preferences the kernel loads at boot are built into the image.

Every file body gets a trailing NUL that size does not count, so a text
file can be handed to a parser as a C string without copying it.
"""

import os
import sys


def collect(root):
    """Nodes as (name, path, parent, isdir, bytes) in directory-first order."""
    nodes = [("/", "", None, True, b"")]

    def walk(rel, parent):
        base = os.path.join(root, rel) if rel else root
        try:
            entries = sorted(os.listdir(base))
        except OSError:
            return
        for name in entries:
            full = os.path.join(base, name)
            path = "{}/{}".format(rel, name) if rel else name
            if os.path.isdir(full):
                idx = len(nodes)
                nodes.append((name, path, parent, True, b""))
                walk(path, idx)
            elif os.path.isfile(full):
                with open(full, "rb") as fh:
                    nodes.append((name, path, parent, False, fh.read()))

    walk("", 0)
    return nodes


def emit_c(nodes, out):
    lines = []
    lines.append("/* Generated by tools/mkpfs.py -- do not edit. */")
    lines.append('#include "pfs.h"')
    lines.append("")

    for i, (_name, path, _parent, isdir, body) in enumerate(nodes):
        if isdir:
            continue
        data = list(body) + [0]
        lines.append("static const unsigned char d%u[] = {" % i)
        for j in range(0, len(data), 16):
            chunk = ", ".join("0x%02x" % b for b in data[j:j + 16])
            lines.append("    " + chunk + ",")
        lines.append("};")
        lines.append("")

    lines.append("const struct pfs_node nb_pfs_nodes[] = {")
    for i, (name, path, parent, isdir, body) in enumerate(nodes):
        p = "PFS_NONE" if parent is None else "%du" % parent
        if isdir:
            data, size = "0", "0"
        else:
            data, size = "d%u" % i, "%du" % len(body)
        lines.append('    { "%s", "%s", %s, %s, %s, %du },' %
                     (name, path, p, data, size, 1 if isdir else 0))
    lines.append("};")
    lines.append("")
    lines.append("const unsigned nb_pfs_count = %u;" % len(nodes))
    lines.append("")

    with open(out, "w") as fh:
        fh.write("\n".join(lines))


def main(argv):
    if len(argv) != 3:
        sys.stderr.write("usage: mkpfs.py <system-dir> <output.c>\n")
        return 2
    root, out = argv[1], argv[2]
    if not os.path.isdir(root):
        sys.stderr.write("mkpfs.py: %s: no such directory\n" % root)
        return 1
    nodes = collect(root)
    emit_c(nodes, out)
    files = sum(1 for n in nodes if not n[3])
    size = sum(len(n[4]) for n in nodes)
    print("mkpfs: %u nodes, %u files, %u bytes -> %s"
          % (len(nodes), files, size, out))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
